Kafka collector script to gather Kafka cluster configuration details
aiven/aiven-examples pull request #100
Opened 2023-12-06 01:01 UTC by runwuf

# Update this heading, and describe your changes

2023-12-06 01:02 UTC, runwuf commented
to run this script you need to have kafka CLI
for Aiven Kafka you can generate configs with `avn service user-kafka-java-creds service --username avnadmin`

2023-12-07 11:50 UTC, paulgrainger-aiven requested changes
please fix hardcoding

2023-12-11 16:12 UTC, runwuf commented on solutions/scripts/kafka-collector.sh
> +    ${KAFKA_HOME}/bin/kafka-consumer-groups.sh --bootstrap-server ${KAFKA_URI} --describe --all-groups --command-config ./client.properties
Thanks for catching this one @paulgrainger-aiven

2023-12-11 17:25 UTC, paulgrainger-aiven approved these changes

2023-12-11 17:26 UTC, merged