clickhouse dbt demo
aiven/aiven-examples pull request #102
Opened 2023-12-16 06:00 UTC by runwuf

This demostrates how to integrate dbt with clickhouse and run a Simple View Materialization demo.

2024-01-11 18:53 UTC, aris-aiven commented
Hey @runwuf, I haven't forgotten about your PR and will try to look at it and run it tomorrow (otherwise beginning of next week)

2024-01-12 04:52 UTC, runwuf commented
No worries, thanks so much @aris-aiven !

2024-03-05 09:27 UTC, aris-aiven requested changes
Awesome work @runwuf!

Left two stylistic comments but except for that it's good to merge on my side

2024-03-05 09:27 UTC, aris-aiven commented on solutions/clickhouse-dbt/ch-dbt.sh
> +pip install dbt-clickhouse
Would be create to have these packages installed in a virtual env

2024-03-05 09:27 UTC, aris-aiven commented on solutions/clickhouse-dbt/ch-dbt.sh
Would be neat to reformat the file to ident the functions, would greatly improve readability

2024-03-21 10:06 UTC, aris-aiven approved these changes
Looks great, thank you for the demo!

2024-03-21 10:06 UTC, merged