Add instruction for OpenSearch training
aiven/aiven-examples pull request #85
Opened 2023-04-14 14:02 UTC by anelook

To make it easier for training instructors, and if we want to share examples with the attendees, I put them all together

2023-04-15 05:54 UTC, runwuf commented
Thanks @anelook! I'm thinking perhaps examples for training / workshop could go under `workshops` or `trainings`, what do you think? maybe need a discussion in a wider audience? what do you think?
I'll continue my review this weekend.

2023-04-17 16:41 UTC, anelook commented
@runwuf , yes, sounds good to me! I didn't see existing folder with trainings, so I created a new one. Let me know if you think we should put it elsewhere

2023-04-19 04:00 UTC, runwuf requested changes
Hi @anelook minor suggestions added.
Also, I have created a script to automate services and configs creation.

2023-04-19 04:04 UTC, runwuf commented
@anelook - thoughts on changing `open-search-1` directory name to a something like `opensearch-kafka-connect-measurements`? as this example could be re-used in your other workshop / event not specific as `course-1`?

2023-04-20 06:51 UTC, anelook commented on trainings/open-search-part-1/buildings.sh
Agree, moved it there

2023-04-20 06:53 UTC, anelook commented on trainings/open-search-part-1/README.md
> +
done!

2023-04-20 14:07 UTC, runwuf approved these changes

2023-04-20 14:07 UTC, merged