Kafka Modern C++ Example
aiven/aiven-examples pull request #98
Opened 2023-11-22 22:05 UTC by runwuf

Kafka Modern C++ Example uses modern-cpp-kafka

2023-11-22 22:31 UTC, tkren requested changes
LGTM, I guess we should run this through some linter

2023-11-22 22:31 UTC, tkren commented on kafka/cc/avn_KafkaConsumer_Simple.cc
> +    consumer.close();
```suggestion
    // Create a consumer instance
    // No explicit consumer.close() is needed, RAII will take care of it
    KafkaConsumer consumer(props);

    // Subscribe to topics
    consumer.subscribe({topic});

    while (running) {
        // Poll messages from Kafka brokers
        auto records = consumer.poll(std::chrono::milliseconds(100));

        for (const auto& record: records) {
            if (!record.error()) {
                std::cout << "Got a new message..." << std::endl;
                std::cout << "    Topic    : " << record.topic() << std::endl;
                std::cout << "    Partition: " << record.partition() << std::endl;
                std::cout << "    Offset   : " << record.offset() << std::endl;
                std::cout << "    Timestamp: " << record.timestamp().toString() << std::endl;
                std::cout << "    Headers  : " << toString(record.headers()) << std::endl;
                std::cout << "    Key   [" << record.key().toString() << "]" << std::endl;
                std::cout << "    Value [" << record.value().toString() << "]" << std::endl;
            } else {
                std::cerr << record.toString() << std::endl;
            }
        }
    }
```

2023-11-22 22:31 UTC, tkren commented on kafka/cc/avn_KafkaConsumer_Simple.cc
> +                std::cerr << record.toString() << std::endl;
I guess we need to dump some sort of error message here? Maybe even bail out early?

2023-11-22 22:31 UTC, tkren commented on kafka/cc/avn_KafkaProducer_Simple.cc
> +        }
same as above

2023-11-22 22:31 UTC, tkren commented on kafka/cc/config.hh
> +});
"feels" better this way:
```suggestion
extern const kafka::Properties props({
                    {"bootstrap.servers", {getenv("KAFKA_BROKER_LIST")}},
                    {"security.protocol", {getenv("SECURITY_PROTOCOL")}},
                    {"ssl.ca.location"  , {getenv("SSL_CA_LOCATION")}},
                    {"ssl.certificate.location" , {getenv("SSL_CERTIFICATE_LOCATION")}},
                    {"ssl.key.location"         , {getenv("SSL_KEY_LOCATION")}}
});
```

2023-11-23 18:15 UTC, runwuf commented on kafka/cc/avn_KafkaProducer_Simple.cc
> +        }
producer.close takes care of errors
```
    const Error result = flush(timeout);
    if (result.value() == RD_KAFKA_RESP_ERR__TIMED_OUT)
    {
        KAFKA_API_DO_LOG(Log::Level::Notice, "purge messages before close, outQLen[%d]", rd_kafka_outq_len(getClientHandle()));
        purge();
    }
```

2023-11-29 00:34 UTC, runwuf commented on kafka/cc/avn_KafkaProducer_Simple.cc
> +std::atomic_bool running = {true};
@aiven-sal appreciate the feedback, I learned something new!
https://en.cppreference.com/w/cpp/atomic/atomic_flag

2023-11-30 05:50 UTC, runwuf commented on kafka/cc/avn_KafkaConsumer_Simple.cc
> +    if (!stop.test_and_set()) {
💯 !! not sure what I was thinking... need more coffee 🤦

2023-11-30 16:17 UTC, runwuf commented on kafka/cc/ccexample.env
> +export SSL_KEY_LOCATION="./service.key"
just checked all the files again, should be all good now 🙏

2023-12-01 16:08 UTC, merged